func f(var int a) int {
    for var int b = 0; b < 10; b = b+1 {
      var int i = 10;
      b = 10;
    }

    var int b = a + 10 - 5.;
    return a;
}

var int a = 0;

func g() {
    var int b = 0;
    var int a = a + 1;
    if a == 1 {
        var int b = 10;
    }

    {
        var int a = 1;
    }
}

func h() {
    if true {
        var int a = 3;
    }
    else if false {
        var int b = 4;
    }
    else if false {
        var int b = 5;
    }
}

func main() {

}