FROM debian:10

# Install build-essential for compiler basics and python.
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
        build-essential \
        python \
    && rm -rf /var/lib/apt/lists/*

# Install packages related to LLVM toolchain
RUN apt-get update \
    && apt-get install -y \
        zlib1g-dev \
        ninja-build \
        cmake \
        llvm \
        clang

CMD ["/bin/bash"]