FROM debian:10

# Install build-essential for compiler basics, python, gdb for debugging,
# and openssh-server and rsync for remote development
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
        build-essential \
        gdb \
        gdbserver \
        python \
        openssh-server \
        rsync \
        valgrind \
    && rm -rf /var/lib/apt/lists/*

# Install packages related to LLVM toolchain
RUN apt-get update \
    && apt-get install -y \
        zlib1g-dev \
        ninja-build \
        cmake \
        llvm \
        clang

# Taken from: https://austinmorlan.com/posts/docker_clion_development/

# Taken from - https://docs.docker.com/engine/examples/running_ssh_service/#environment-variables
RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

# 22 for ssh server. 7777 for gdb server.
EXPOSE 22 7777

# Create dev user with password 'dev'
RUN useradd -ms /bin/bash dev
RUN echo 'dev:dev' | chpasswd

# Upon start, run ssh daemon
CMD ["/usr/sbin/sshd", "-D"]
